name: Node.js CI/CD
on:
  push:
    branches: [ "main" ]
jobs:
  build:
    runs-on: self-hosted
    strategy:
      matrix:
        # Choose one Node.js version instead of multiple
        node-version: [22.x]  # Or whichever version you prefer
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - name: Start/Restart PM2
      run: |
        pm2 describe BackendAPI > /dev/null
        if [ $? -eq 0 ]; then
          pm2 restart BackendAPI
        else
          pm2 start index.js --name BackendAPI
        fi
